name: tie_picker
description: Minimalist pickers
version: 0.0.1
homepage: https://github.com/unacorbatanegra/tie_picker

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0" 

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  occam: ^0.0.5
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

