name: tie_picker
description: Minimalist pickers
version: 0.0.1
homepage: https://github.com/unacorbatanegra/tie_picker
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter

  gap: ^3.0.0
  intl: ^0.18.0
  occam: ^1.0.0
  flutter_localizations: 
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  generate: true
