name: tie_picker
description: Minimalist Calendar & Time & Custom pickers
version: 0.0.3
homepage: https://github.com/unacorbatanegra/tie_picker

environment:
  sdk: ">=3.1.0 <4.0.0"
  # flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter

  gap: ^3.0.0
  intl: ^0.19.0
  occam: ^1.0.0
  flutter_localizations: 
    sdk: flutter
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  generate: true
